settings:
  title: 'Status Page'
  url: 'https://status-page.duhost.workers.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
#  - id: val # unique identifier
#    name: Valhallaa
#    url: 'https://valhallaa.tk/' # URL to fetch
#    method: GET # default=GET
#    expectStatus: 200 # operational status, default=200
#    followRedirect: false # should fetch follow redirects, default=false
#    linkable: true # allows the title to be a link, default=true
    
  - id: nyaa # unique identifier
    name: Nyaa
    url: 'https://nyaa.deno.dev/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
    
  - id: nginx # unique identifier
    name: NL1
    url: 'https://nl.uiaal.cf/' # URL to fetch
    method: GET # default=GET
    expectStatus: 403 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true   
    
  - id: NL1vless # unique identifier
    name: DexVPN Websocket
    url: 'https://ws1.lamax.tk/vlws' # URL to fetch
    method: GET # default=GET
    expectStatus: 400 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
    
    

  #- id: cloudflared # unique identifier
   # name: Cloudflare Tunnel
   # url: 'https://hello.valhallaa.tk/' # URL to fetch
   # method: GET # default=GET
   # expectStatus: 200 # operational status, default=200
   # followRedirect: false # should fetch follow redirects, default=false
   # linkable: false # allows the title to be a link, default=true
    
  #- id: fsb # unique identifier
   # name: File Streamer Bot
   # url: 'https://fsb-est1.fandogh.cloud/' # URL to fetch
   # method: GET # default=GET
   # expectStatus: 200 # operational status, default=200
   # followRedirect: false # should fetch follow redirects, default=false
   # linkable: false # allows the title to be a link, default=true

  #- id: twb # unique identifier
   # name: Twitch Bot
   # url: 'https://tw.valhallaa.tk/' # URL to fetch
   # method: GET # default=GET
   # expectStatus: 200 # operational status, default=200
   # followRedirect: false # should fetch follow redirects, default=false
   # linkable: false # allows the title to be a link, default=true
    
  #- id: de1 # unique identifier
   # name: DE 1
   # url: 'https://ladorrbas.ml/tj' # URL to fetch
   # method: GET # default=GET
   # expectStatus: 200 # operational status, default=200
   # followRedirect: false # should fetch follow redirects, default=false
   # linkable: false # allows the title to be a link, default=true   
  

  #- id: uk1 # unique identifier
   # name: UK 1
   # url: 'https://alkgwmoawjt.cf/tj' # URL to fetch
   # method: GET # default=GET
   # expectStatus: 200 # operational status, default=200
   # followRedirect: false # should fetch follow redirects, default=false
   # linkable: false # allows the title to be a link, default=true 
